# -*- coding: utf-8 -*-
"""Ordinary Least Square.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vsdnODNNQChO5b9E4hP-Ba0pXafgJI1y
"""

import numpy as np
import pandas as pd


data = pd.read_csv("https://raw.githubusercontent.com/sarthak0906/Ordinary-Least-Square/master/Admission_Predict.csv")
mean = data.mean()
data.plot()
# print((mean.SOP))
# print(data.mean().SOP)

m = {}
df = data.head(399)
df.drop(["Serial No."], axis=1)

for col in df.drop(["Serial No."], axis=1).columns:
  if (col != "Chance of Admit "):
    m[col] = (((df[col] - df[col].mean()).multiply(df['Chance of Admit '] - df['Chance of Admit '].mean())).sum()) / ((df[col] - df[col].mean()).pow(2).sum())

mean = data.mean()
b = mean["Chance of Admit "]

for col in df.drop(["Serial No."], axis=1).columns:
  if (col != "Chance of Admit "):
    b = b - (mean[col] * m[col])

b

data = pd.read_csv("https://raw.githubusercontent.com/sarthak0906/Ordinary-Least-Square/master/Admission_Predict_Ver1.1.csv")

m["Serial No."] = 0
n = 0
delta = 0
for index, row in data.iterrows():
  value = b
  for col in data.columns:
    if (col != "Chance of Admit "):
      value = value + (row[col] * m[col])
    else :
      delta = delta + (row[col] - value)
      n = n + 1

accuracy = delta / n
accuracy = (1 - accuracy) * 100
accuracy